config/routes.rb
Rails.application.routes.draw do

	devise_for :admin_users, ActiveAdmin::Devise.config
	ActiveAdmin.routes(self)

  resources 'finder', only: [:index, :alphabetized, :missing_email]

  get 'customer/missing_email' => 'finder#missing_email'
  #load cust page
  root to: 'finder#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
	belongs_to :province
	validates :name, presence: true 
end

app/models/province.rb
class Province < ApplicationRecord
	has_many :customers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
  	@customers = Customer.all
  end

  def show
  	@customer = Customer.find(params[:id])
  end
end

app/controllers/finder_controller.rb
class FinderController < ApplicationController
  def index
  	@customers = Customer.all
  end

  def alphabetized
  	@customersA = Customer.all.order(name: :desc)
  end

  def missing_email
  	@missing_email = Customer.where("email_address == ''").all()
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/finder_helper.rb
module FinderHelper
end

app/views/customers/_customer.html.slim
.customer
	h2 = customer.name
	p = image_tag customer.image, height:'200', width:'150'
	p 
		strong> Phone: 
		= customer.phone_number
	p 
		strong> Email: 
		= customer.email_address	
	p 
		strong> Notes: 
		= customer.notes
	p = link_to 'details', customer

app/views/customers/index.html.slim
h1 All Customers
ul
	li = link_to 'New Customer '
	li = link_to '- Missing Emails'

	= render partial: 'customer', collection: @customers

app/views/customers/show.html.slim
= render partial: 'customer', object: @customer

p = link_to 'Home', root_path

app/views/finder/_customer.html.slim
.customer
	h2 = customer.name
	p = image_tag customer.image, height:'200', width:'150'
	p 
		strong> Phone: 
		= customer.phone_number
	p 
		strong> Email: 
		= customer.email_address	
	p
		strong> Province:
		= customer.province
	p 
		strong> Notes: 
		= customer.notes
	

app/views/finder/_li.html.slim
li.cust = render partial: 'customer', collection: @customers

app/views/finder/alphabetized.html.slim
h1 Alphabetized Customers
ul
	li = link_to 'New Customer '
	li = link_to '- Missing Emails', missing_email
ul.cust
	li = render partial: 'customer', collection: @customersA

app/views/finder/index.html.slim
#wrapper
	h1 All Customers
	ul
		li = link_to 'New Customer '
		li = link_to '- Missing Emails'
		
	= render partial: 'customer', collection: @customers

app/views/finder/missing_email.html.slim
h1 Customers Missing Emails
ul
	li = link_to 'New Customer '
	li = link_to ' Missing Emails', customer_missing_email_path
ul.cust
	li = render partial: 'customer', collection: @missing_email

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>U7CustomerRealtionManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>